version: '3.8'

services:
  subconverter:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - SERVER_HOST=0.0.0.0
      - LOG_LEVEL=info
      - REDIS_ENABLED=true
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    volumes:
      - ./configs:/root/configs:ro
      - ./templates:/root/templates:ro
      - ./rules:/root/rules:ro
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  worker:
    build: .
    command: ["./subworker", "start", "--workers", "4"]
    environment:
      - REDIS_ENABLED=true
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - QUEUE_TYPE=redis
    depends_on:
      - redis
    restart: unless-stopped

volumes:
  redis_data: