apiVersion: v1
kind: Service
metadata:
  name: subconverter-service
  namespace: subconverter
  labels:
    app: subconverter
spec:
  selector:
    app: subconverter
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    name: http
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: subconverter
  labels:
    app: redis
spec:
  selector:
    app: redis
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
    name: redis
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: subconverter-metrics
  namespace: subconverter
  labels:
    app: subconverter
    service: metrics
spec:
  selector:
    app: subconverter
  ports:
  - protocol: TCP
    port: 9090
    targetPort: 9090
    name: metrics
  type: ClusterIP