server:
  port: 8080
  host: "0.0.0.0"
  mode: "release"

log:
  level: "info"
  format: "json"
  output: "stdout"

redis:
  enabled: false
  host: "localhost"
  port: 6379
  password: ""
  database: 0

cache:
  ttl: 300
  max_size: 1000

security:
  rate_limit:
    enabled: true
    requests: 100
    window: "1m"
  cors:
    enabled: true
    origins:
      - "*"

parser:
  timeout: 30
  max_size: 10485760  # 10MB

generator:
  templates_dir: "./templates"
  rules_dir: "./rules"